### ISSUE TITLE
SW Version error when setting up GE Home Integration

### ISSUE THREAD

**Issue by SSinSD** [simbaja/ha_components#11]
I am getting the following error for SW Version for multiple entities when trying to install GE Home integration:

Logger: homeassistant.components.binary_sensor
Source: custom_components/ge_home/devices/base.py:84
Integration: Binary sensor (documentation, issues)

Error adding entities for domain binary_sensor with platform ge_home
Error while setting up ge_home platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 458, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/ge_home/entities/common/ge_entity.py", line 25, in device_info
    return self.api.device_info
  File "/config/custom_components/ge_home/devices/base.py", line 84, in device_info
    "sw_version": self.appliance.get_erd_value(ErdCode.APPLIANCE_SW_VERSION),
  File "/usr/local/lib/python3.8/site-packages/gehomesdk/ge_appliance.py", line 119, in get_erd_value
    return self._property_cache[erd_code]
KeyError: <ErdCode.APPLIANCE_SW_VERSION: '0x0103'>

**Comment by simbaja** [comment]
Can you run the raw sdk (simbaja/gehomesdk) and see what ERD codes are displaying?  It should always have the software version, but perhaps your particular models don't report that?

**Comment by simbaja** [comment]
I think both should be ok, one is trying to get the wifi sw version, the other for the appliance itself.  For my appliance (and apparently Warren's at least) we get both, but thought it made more sense to use the appliance version for a device.  This might be model specific though.

**Comment by SSinSD** [comment]
I will see what I can do running the raw SDK later tonight (I'm not a programmer by trade, so I'm reaching the limit of my abilities).  None of my appliances were showing version numbers before (all showed 0.0.0.0) and my oven would not add at all.  I manually changed the line of code in base.py back to WIFI_MODULE_SW_VERSION, now I see version numbers and my oven added properly.

**Comment by simbaja** [comment]
Sounds good.  Probably a model thing, but if we can figure out what code(s) it is sending, that would be best.  We can probably add some more error handling so that we don't run into a problem with this.  Out of curiosity, which appliances do you have?

**Comment by simbaja** [comment]
Try now, the latest version should have some error handling and will include both firmware versions.  Hopefully all works now for you.

**Comment by SSinSD** [comment]
I tried the latest version and all worked well.  Thank you.  For reference, here are my models:
Dryer GFD65GSPN0SN
Washer  
Dish Washer ZDT925SSN2SS
Oven SNLR119439Q
Fridge ZISS420DNBSS

**Comment by simbaja** [comment]
Glad to hear it works for you now!  Hopefully, you get a chance to run the SDK since those look like models that we haven't seen before.  If you execute the websocket example after putting a secrets.py file in place and copy out the ERD codes, that would be a big help to identifying what your appliances are doing and making any needed adjustments.

**Comment by SSinSD** [comment]
I also have an Advantium (it is microwave/convection oven).  I ran the websocket example, I saved the log file.  Is this what you are looking for?
[gehomesdk.log](https://github.com/simbaja/ha_components/files/6628215/gehomesdk.log)

**Comment by simbaja** [comment]
Yep, that's what I was looking for, perfect.  As expected, a couple of your appliances aren't reporting an appliance version, which is interesting.  Also, we don't have anyone else (that I know about) that has an Advantium, so I'll look into some of these codes and try and get more of it available in HA.  

We also seem to have some new laundry codes, @warrenrees, have you seen the codes in this log before?

**Comment by SSinSD** [comment]
Is there something I can do on my end to help translate what the codes mean to help you out?  Thanks to you both for working on this!

**Comment by SSinSD** [comment]
Simbaja, I believe the issue on SW version is now closed, I'll jump over to the gehomesdk github and put the info I get from Advantium over there.
