### ISSUE TITLE
Error with GE Home with Cafe Oven

### ISSUE THREAD

**Issue by unsounddabbit** [simbaja/ha_components#14]
I'm getting the following error when setting up my oven.

`This error originated from a custom integration.

Logger: custom_components.ge_home.config_flow
Source: custom_components/ge_home/config_flow.py:33
Integration: GE Home (documentation)
First occurred: 7:32:13 AM (2 occurrences)
Last logged: 8:03:10 AM

Unknown connection failure
Traceback (most recent call last):
  File "/config/custom_components/ge_home/config_flow.py", line 33, in validate_input
    _ = await async_get_oauth2_token(session, data[CONF_USERNAME], data[CONF_PASSWORD])
  File "/usr/local/lib/python3.8/site-packages/gehomesdk/clients/async_login_flows.py", line 55, in async_get_oauth2_token
    code = parse_qs(urlparse(resp.headers['Location']).query)['code'][0]
KeyError: 'Location'
`

I'm getting some warning about sabbath switch also, but I think it may be related to this.

`Logger: homeassistant.helpers.service
Source: helpers/service.py:128
First occurred: 7:39:08 AM (2 occurrences)
Last logged: 7:39:11 AM

Unable to find referenced entities switch.shvh173907p_sabbath_mode`

I also have the following warning.

`Logger: slixmpp.stringprep
Source: /usr/local/lib/python3.8/site-packages/slixmpp/stringprep.py:120
First occurred: 7:15:43 AM (1 occurrences)
Last logged: 7:15:43 AM

Using slower stringprep, consider compiling the faster cython/libidn one.`

FYI, I'm running this in docker and installed HACS through the docker container.  The oven controls are also coming up as water heater controls.

**Comment by simbaja** [comment]
The second warning is ok, it's just saying it's using a slower version.  The oven controls (and frankly most things that have adjustable temperatures) will come up as a water heater.  Unfortunately, HA doesn't have the appropriate entity type, so we have to make do with what we have :).

In terms of that first error, do you happen to have a special character in your password or username (beyond @)?  If so, can you try removing the special character and see if that fixes it?  If so, can you let me know what character it is?

**Comment by unsounddabbit** [comment]
Yeah,

I figured GE would use the same parts for multiple devices.  I mean, in the
end it's adjusting the temp for a heater.  You wouldn't need to make 10
different switches for that.

The character is # in the password.  The SmartHQ app requires a special
character in the password.  The examples it lists are $, &, %, and @.  I
used #.  It works so it's not a big deal.   I just have an error on my
integrations page.   It may be a good idea to accept all of the special
characters on the number row.  One thing that would be nice is if you could
set a temp by typing a number instead of incrementing by 1. Is this even
possible with the api?  Perhaps I should put that on a new thread, but I'm
not using my computer at the moment.

**Comment by unsounddabbit** [comment]
FWIW, I no longer get the error after the latest update.  Thank you for this.  It works great!

**Comment by simbaja** [comment]
Thanks for confirming!
