### ISSUE TITLE
Two Refrigerator binary_sensors appear to do nothing: ice_maker_control_status & door_status_any_open

### ISSUE THREAD

**Issue by joelmoses** [simbaja/ha_components#6]
I'm tracking this one down, but it looks like they should just be "On" if the ice maker is enabled and "On" if any one of the doors to the refrigerator or freezer are open. Instead, the Door binary_sensor defaults to "Closed" continuously regardless of actions, and the Ice Maker control status always reports "Off".

I can see in the SDK where they're instrumented - both as a property. But they seem to not see events in the HA component.

**Comment by simbaja** [comment]
This should be resolved as of the latest "dev" version.
